name: Packer Format

on:
  pull_request:
    branches: [testing]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: create and configure
      run: |
        touch .env
        echo port=${{ secrets.PORT }} >> .env
        echo host=${{ secrets.HOST }} >> .env
        echo dialect=${{ secrets.DIALECT }} >> .env
        echo user=${{ secrets.USER }} >> .env
        echo password=${{ secrets.PASSWORD }} >> .env
        echo database=${{ secrets.DATABASE }} >> .env
    - name: Set up Packer
      run: |
        wget -O packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
        unzip packer.zip
        chmod +x packer
        sudo mv packer /usr/local/bin/
        packer version
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Run Packer plugin installation
      run: packer init .

    - name: Check Packer template format
      run: packer fmt -check ami.us-east-1.pkr.hcl

      