name: Check Packer Format

on:
  push:
  pull_request:

jobs:
  connect-remote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Environment Variables
        run: |
          echo "Setting up environment variables..."
          touch .env
          echo port=${{ secrets.PORT }} >> .env
          echo host=${{ secrets.HOST }} >> .env
          echo dialect=${{ secrets.DIALECT }} >> .env
          echo user=${{ secrets.USER }} >> .env
          echo password=${{ secrets.PASSWORD }} >> .env
          echo database=${{ secrets.DATABASE }} >> .env

      - name: Install dependencies
        run: |
          echo "Installing npm dependencies..."
          npm install

      - name: Wait for MySQL to become available
        run: |
          echo "Waiting for MySQL..."
          for i in {1..30}; do
            nc -z -v -w5 ${{ secrets.HOST }} 3306 && echo "MySQL is up" && break
            echo "Waiting for MySQL... $i/30"
            sleep 5
          done

      - name: Run tests
        run: |
          echo "Running tests..."
          npm test

      - name: Set up Packer
        run: |
          echo "Setting up Packer..."
          wget -O packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
          unzip packer.zip
          chmod +x packer
          sudo mv packer /usr/local/bin/
          packer version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run Packer plugin installation
        run: |
          echo "Initializing Packer..."
          packer init .

      - name: Check Packer template format
        run: |
          echo "Checking Packer template format..."
          packer fmt -check ami-packer.hcl
